app/repositories/HeldSubmissionRepository.scala
it/repositories/HeldSubmissionMongoRepositoryISpec.scala
test/helpers/MongoMocks.scala
test/repositories/HeldSubmissionRepositorySpec.scala

SCRS-2283 held repo

---

app/config/MicroserviceAppConfig.scala
app/config/Module.scala
app/connectors/IncorporationInformationConnector.scala
app/controllers/admin/AdminController.scala
app/repositories/HeldSubmissionRepository.scala
app/services/admin/AdminService.scala
conf/admin.routes
it/api/AdminApiISpec.scala
test/auth/AuthorisationSpec.scala
test/connectors/IncorporationInformationConnectorSpec.scala
test/controllers/admin/AdminControllerSpec.scala
test/services/CorporationTaxRegistrationServiceSpec.scala
test/services/admin/AdminServiceSpec.scala

For manual testing this PR requires company-registration-admin-frontend on branch SCRS-7682 aswell

SCRS-7682 Added held submission migration admin endpoint

---

app/controllers/HeldController.scala
app/models/CorporationTaxRegistration.scala
app/repositories/CorporationTaxRegistrationMongoRepository.scala
it/repositories/CorporationTaxRegistrationMongoRepositoryISpec.scala
test/controllers/HeldControllerSpec.scala

- Added optional "heldTimestamp" to CR doc and atomically set it when updating the record to held at the end of the HO6 processing

SCRS-8896 Added held time stamp to CR doc

---

app/repositories/CorporationTaxRegistrationMongoRepository.scala
app/services/admin/AdminService.scala
conf/application.conf
it/repositories/CorporationTaxRegistrationMongoRepositoryISpec.scala
test/services/admin/AdminServiceSpec.scala

Moved retention date to config

---

app/repositories/CorporationTaxRegistrationMongoRepository.scala
app/repositories/HeldSubmissionRepository.scala
app/repositories/SequenceMongoRepository.scala
app/repositories/StateDataRepository.scala
app/repositories/ThrottleMongoRepository.scala

Annotated each repository, added logging on instantiation

---

project/MicroServiceBuild.scala
project/build.properties

*SCRS-11380*
**Dependency Uplift**
Uplifted dependencies and sbt version.

SCRS-11380 Uplifted dependencies

---

app/controllers/ProcessIncorporationsController.scala
app/services/RegistrationHoldingPenService.scala
it/api/ProcessIncorporationsControllerISpec.scala
project/plugins.sbt

SCRS-11615 Fix for rejected incorps with no CT document
Bug fix to cancel the II subscription for rejected incorps with no CT document

SCRS-11615 Fix for rejected incorps with no CT document

---

app/config/microserviceGlobal.scala

SCRS-11802 get txid from ackref
**Bug fix / 
Supply an ackref and get the transid and regid
* [X ] I've executed the acceptance test pack locally to ensure there are no regressions
* [ X] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
* [ X] I've run a dependency check to ensure all dependencies are up to date

SCRS-11802 get txid from ackref

---

app/config/microserviceGlobal.scala
project/MicroService.scala

**Bug fix**
Adding trigger that was missed on original PR.

SCRS-11897 Added trigger for start up job

---

app/controllers/admin/AdminController.scala

**New feature**
Extra logging around admin endpoint for CR

SCRS-11585 Added additional logging around admin endpoint for CR

---

app/audit/DesTopUpEvent.scala
app/repositories/CorporationTaxRegistrationMongoRepository.scala
app/services/admin/AdminService.scala
it/itutil/WiremockHelper.scala
it/jobs/RemoveStaleDocumentsJobISpec.scala
it/repositories/CorporationTaxRegistrationMongoRepositoryISpec.scala
test/services/RegistrationHoldingPenServiceSpec.scala
test/services/admin/AdminServiceSpec.scala

**Bug fix**
Take in account Held/Locked document for the RemoveStaleDoc job to be compliant with GDPR.

[SCRS-11497] Added held stale doc processing and extra audit event with new field

---

app/connectors/IncorporationInformationConnector.scala
app/services/admin/AdminService.scala
app/utils/AlertLogging.scala
project/MicroServiceBuild.scala
test/connectors/IncorporationInformationConnectorSpec.scala
test/services/admin/AdminServiceSpec.scala

**Bug fix**
refactored the code to not use exception at connector level + update pager duty content

[SCRS-11497] Refactor code + update pager duty from NINETY_DAYS_DELETE_WARNING_CRN_FOUND to STALE_DOCUMENTS_DELETE_WARNING_CRN_FOUND

---

app/repositories/CorporationTaxRegistrationMongoRepository.scala

New feature
Added logging to fetch status method.

SCRS-11585b Added logging for fetch status

---

app/controllers/ProcessIncorporationsController.scala
app/controllers/test/SubmissionCheckController.scala
app/services/RegistrationHoldingPenService.scala
app/services/SendEmailService.scala
app/services/UserAccessService.scala
app/utils/AlertLogging.scala
it/api/ProcessIncorporationsControllerISpec.scala
project/plugins.sbt
test/controllers/ProcessIncorporationsControllerSpec.scala
test/services/RegistrationHoldingPenServiceSpec.scala

**New feature**
Amended the response sent to II and added Pager Duty Log

Scrs 11804

---

test/services/RegistrationHoldingPenServiceSpec.scala

**New feature**
fix test which was using in correct working days guard

[SCRS-11804] quick test refactor

---

project/MicroService.scala
project/MicroServiceBuild.scala
project/plugins.sbt

Amended for new build server, also removed unused resolver

SCRS-11994 amended for new build server and removed play url binders

---

app/config/microserviceGlobal.scala
conf/admin.routes
test/config/AppStartupJobsSpec.scala

**New feature**
We have a document living in Production that does not contain all the information we would expect for it's status. This code change should allow us to gather a better understanding of the shape of this document.

SCRS-12070 Added start up job to print info about given RegIds  

---

conf/application.conf

SCRS-12087 Updates for protocol change to https

SCRS-12087 Updates for protocol change to https

---

app/controllers/admin/AdminController.scala
app/models/CorporationTaxRegistration.scala
app/services/admin/AdminService.scala
it/api/AdminApiISpec.scala
test/controllers/admin/AdminControllerSpec.scala
test/services/admin/AdminServiceSpec.scala

**Enhancement** 
See JIRA ticket for more information. Current sessionID admin endpoints enhanced to include sessionID.

SCRS-12069 Updated admin endpoint to accept cred id

---

app/connectors/DesConnector.scala
it/api/ProcessIncorporationsControllerISpec.scala
it/api/SubmissionControllerISpec.scala
project/MicroServiceBuild.scala
project/plugins.sbt
test/connectors/DesConnectorSpec.scala

SCRS-12154 added 429 case statement to return 503 plus dep uplift and added hmrc releases resolvers

---

project/MicroServiceBuild.scala
project/plugins.sbt

SCRS-12697b - dependency uplift## Checklist

SCRS-12697b - dependency uplift

---

app/auth/AuthorisedActions.scala
app/config/Module.scala
app/controllers/AccountingDetailsController.scala
app/controllers/CorporationTaxRegistrationController.scala
app/controllers/GroupsController.scala
app/models/CorporationTaxRegistration.scala
app/models/Groups.scala
app/models/des/InterimDesRegistration.scala
app/models/validation/APIValidation.scala
app/models/validation/BaseJsonFormatting.scala
app/models/validation/MongoValidation.scala
app/repositories/CorporationTaxRegistrationMongoRepository.scala
app/services/CorporationTaxRegistrationService.scala
app/services/GroupsService.scala
conf/app.routes
it/api/GroupsControllerISpec.scala
it/api/RegistrationProgressISpec.scala
it/repositories/CorporationTaxRegistrationMongoRepositoryISpec.scala
project/MicroServiceBuild.scala
project/plugins.sbt
test/controllers/CorporationTaxRegistrationControllerSpec.scala
test/controllers/GroupsControllerSpec.scala
test/mocks/SCRSMocks.scala
test/models/GroupsSpec.scala
test/models/IncorporationInformationSpec.scala
test/services/CorporationTaxRegistrationServiceSpec.scala
test/services/GroupsServiceSpec.scala

Added in groups saving, updating deleteing, convert ro to business address, list of group names validation endpoint and dep uplift

Scrs 12863

---

app/models/des/InterimDesRegistration.scala
app/repositories/CorporationTaxRegistrationMongoRepository.scala
app/services/CorporationTaxRegistrationService.scala
app/services/GroupsService.scala
app/services/SubmissionService.scala
it/api/SubmissionControllerISpec.scala
it/repositories/CorporationTaxRegistrationMongoRepositoryISpec.scala
project/MicroServiceBuild.scala
project/plugins.sbt
test/models/des/InterimDesRegistrationSpec.scala
test/services/CorporationTaxRegistrationServiceSpec.scala
test/services/SubmissionServiceSpec.scala

Cant run AT's as local env playing up, please squash before merge, added Groups des submission. ONLY normalising NAME as address should already be saved normalised.

Scrs 12873 des

---

project/MicroServiceBuild.scala
project/plugins.sbt

SAR-4117 dep uplift with temp mac workaround for mongo

---

conf/application.conf

SAR-4341 Handling SSLEngine closed already exceptions

---

app/models/Address.scala
app/models/CorporationTaxRegistration.scala
app/models/TakeoverDetails.scala
test/assets/TestConstants.scala
test/fixtures/CorporationTaxRegistrationFixture.scala
test/models/AddressSpec.scala
test/models/CorporationTaxRegistrationSpec.scala
test/models/TakeoverDetailsSpec.scala

SAR-4413: Add takeover details to CTR model
**New feature** (delete as appropriate)
- Added new TakeoverDetails and Address models
- Updated CompanyTaxRegistration model to include an optional TakeoverDetails section
- Unable to run acceptance tests due to an issue (fixing in progress)

SAR-4413: Add takeover details to CTR model

---

app/models/Address.scala
app/models/des/InterimDesRegistration.scala
app/services/SubmissionService.scala
it/api/SubmissionControllerISpec.scala
it/itutil/ItTestConstants.scala
test/assets/TestConstants.scala
test/models/AddressSpec.scala
test/models/des/InterimDesRegistrationSpec.scala

SAR-4432 Added in takeover block to DES submission
New feature
Note that the Address model has been updated to make line 2 mandatory

SAR-4432 Added in takeover block to DES submission

---

app/config/Module.scala
app/controllers/TakeoverDetailsController.scala
app/services/TakeoverDetailsService.scala
conf/app.routes
it/api/TakeoverDetailsControllerISpec.scala
test/controllers/TakeoverDetailsControllerSpec.scala

SAR-4415 created the TakeoverDetails controller, updated routes

---

app/models/des/InterimDesRegistration.scala
it/api/SubmissionControllerISpec.scala
test/services/SubmissionServiceSpec.scala

SAR-5253: Update to properly build takeovers block

---

app/models/validation/BaseJsonFormatting.scala
test/audit/DesSubmissionEventSpec.scala
test/models/CorporationTaxRegistrationSpec.scala

SAR-5242 Updated the forbidden punctuation regex and added an exhaustive scalacheck test for companyname validation

---

app/services/SubmissionService.scala
test/services/SubmissionServiceSpec.scala

SAR-5739 - Remove illegal chars on group address before DES submission

---

app/models/des/InterimDesRegistration.scala
app/services/SubmissionService.scala
test/services/SubmissionServiceSpec.scala

Reverts hmrc/company-registration#286

Revert "SAR-5739 - Remove illegal chars on group address before DES submission"

---

it/jobs/RemoveStaleDocumentsJobISpec.scala
test/services/admin/AdminServiceSpec.scala

SAR-6925: Update to allow list

---

it/jobs/RemoveStaleDocumentsJobISpec.scala

Fix to ittest after mongo 4.2 upgrade

---

app/config/LangConstants.scala
app/config/MicroserviceAppConfig.scala
app/config/Module.scala
app/services/ProcessIncorporationService.scala
app/services/SendEmailService.scala
app/services/UserAccessService.scala
conf/application.conf
it/api/CompanyDetailsApiISpec.scala
it/api/ProcessIncorporationsControllerISpec.scala
it/api/SubmissionControllerISpec.scala
it/api/TakeoverDetailsControllerISpec.scala
it/itutil/ItTestConstants.scala
it/jobs/RemoveStaleDocumentsJobISpec.scala
it/repositories/CTUTRMongoRepositoryISpec.scala
it/repositories/CorporationTaxRegistrationMongoRepositoryISpec.scala
test/assets/TestConstants.scala
test/config/AppStartupJobsSpec.scala
test/config/LangConstantsSpec.scala
test/fixtures/CorporationTaxRegistrationFixture.scala
test/services/CorporationTaxRegistrationServiceSpec.scala
test/services/ProcessIncorporationServiceSpec.scala
test/services/SendEmailServiceSpec.scala
test/services/SubmissionServiceSpec.scala
test/services/admin/AdminServiceSpec.scala

Feature flags for environments:
- QA: https://github.com/hmrc/app-config-qa/pull/16473
- Staging: https://github.com/hmrc/app-config-staging/pull/11440
- Production: https://github.com/hmrc/app-config-production/pull/16285

[SAR-9768] Add Sending of Welsh VAT email begind a Feature Switch

---

app/config/MicroserviceAppConfig.scala
app/services/ProcessIncorporationService.scala
app/services/SendEmailService.scala
conf/application.conf
test/services/ProcessIncorporationServiceSpec.scala
test/services/SendEmailServiceSpec.scala

App-Config-Reverts:
- https://github.com/hmrc/app-config-qa/pull/16482
- https://github.com/hmrc/app-config-staging/pull/11446

[SAR-9768-Revert] Revert the triggering of the Welsh email - as this is handled by DC preference

---

app/auth/AuthorisedActions.scala
app/controllers/LanguageController.scala
app/models/Language.scala
app/repositories/CorporationTaxRegistrationMongoRepository.scala
app/services/LanguageService.scala
conf/app.routes
it/api/LanguageControllerISpec.scala
it/itutil/LogCapturingHelper.scala
it/itutil/WiremockHelper.scala
it/jobs/RemoveStaleDocumentsJobISpec.scala
it/repositories/CorporationTaxRegistrationMongoRepositoryISpec.scala
test/config/AppStartupJobsSpec.scala
test/connectors/IncorporationInformationConnectorSpec.scala
test/controllers/LanguageControllerSpec.scala
test/controllers/ProcessIncorporationsControllerSpec.scala
test/controllers/test/TestEndpointControllerSpec.scala
test/models/GroupsSpec.scala
test/services/CorporationTaxRegistrationServiceSpec.scala
test/services/GroupsServiceSpec.scala
test/services/LanguageServiceSpec.scala
test/services/ProcessIncorporationServiceSpec.scala
test/services/SubmissionServiceSpec.scala
test/utils/AlertLoggingSpec.scala
test/utils/LogCapturingHelper.scala
test/utils/LoggingUtilSpec.scala

**Note:**
- This is dependant on #314 being reviewed and merged first as it requires the LangConstants.

[SARR-10773] Add API to enabled the stored languageCode on the CT document

---

app/models/TakeoverDetails.scala
app/models/validation/APIValidation.scala
app/services/SubmissionService.scala
app/utils/StringNormaliser.scala
test/services/SubmissionServiceSpec.scala

DL-10559 Remove illegal characters from takeover names

---

test/connectors/httpParsers/IncorporationInformationHttpParsersSpec.scala

fix the test pack

---

build.sbt
conf/logback-test.xml
conf/logback.xml
project/AppDependencies.scala
project/build.properties
project/plugins.sbt

[DL-15995] Upgrade for Java 21

---

test/connectors/httpParsers/IncorporationInformationHttpParsersSpec.scala

[TestFix] Fix error level check in test
